/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import retrofit2.Retrofit;
import retrofit2.converter.gson.GsonConverterFactory;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {


        //okhttp client
        OkHttpClient client=new OkHttpClient();

        Request r=new Request.Builder().url("https://jsonplaceholder.typicode.com/todos/1").build();

        try(Response res=client.newCall(r).execute()){
            System.out.println(res.body().string());

        }
        catch (Exception e){
            System.out.println("exception");
        }

        //retrofit client
        //Retrofit does this:
        //
        //Makes HTTP request using OkHttp
        //
        //Receives response body as JSON string
        //
        //Finds GsonConverterFactory
        //
        //Calls internally:

        Retrofit rclient=new Retrofit.Builder().baseUrl("https://jsonplaceholder.typicode.com")
                .addConverterFactory(GsonConverterFactory.create()).build();

        TodoService todoService=rclient.create(TodoService.class);
        Todo t=todoService.getTodoById("1").execute().body();
        System.out.println(t);









    }
}
